apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secdemo

bases:
   - ../../base

patches:
  - path: patch-low-security.json
    target:
      labelSelector: "zone=low"
      kind: Route
  - path: patch-med-security.json
    target:
      labelSelector: "zone=med"
  - path: patch-high-security.json
    target:
      labelSelector: "zone=high"
