apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
   - ../../base

patches:
  - path: https://raw.githubusercontent.com/marouim/route-kustomize-zones/master/manifests/zones/zone_a.yaml
    target:
      labelSelector: zone=zone_a
      kind: Route

  - path: https://raw.githubusercontent.com/marouim/route-kustomize-zones/master/manifests/zones/zone_b.yaml
    target:
      labelSelector: zone=zone_b
      kind: Route

  - path: https://raw.githubusercontent.com/marouim/route-kustomize-zones/master/manifests/zones/zone_c.yaml
    target:
      labelSelector: zone=zone_c
      kind: Route