apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
   - ../../base

patches:
  - path: https://raw.githubusercontent.com/marouim/route-kustomize/master/manifests/overlay/zones/patch-zone-low.yaml
    target:
      labelSelector: zone=low
      kind: Route

  - path: https://raw.githubusercontent.com/marouim/route-kustomize/master/manifests/overlay/zones/patch-zone-medium.yaml
    target:
      labelSelector: zone=medium
      kind: Route