apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
   - ../../base

patches:
  - path: patch-zone-low.yaml
    target:
      labelSelector: zone=low
      kind: Route

  - path: patch-zone-medium.yaml
    target:
      labelSelector: zone=medium
      kind: Route